workflows:
  ios-laser-detector:
    name: LaserDetector
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Install dependencies
        script: echo "No dependencies needed for pure SwiftUI project"
      - name: Build iOS app
        script: xcodebuild -scheme LaserDetector -sdk iphoneos -configuration Release clean build
    artifacts:
      - build/Release-iphoneos/LaserDetector.ipa
    publishing:
      email:
        recipients:
          - djdreamfix@gmail.com
