workflows:
  ios-laser-detector:
    name: LaserDetector iOS
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release" # можна прибрати, якщо чистий SwiftUI
    scripts:
      - name: Install dependencies
        script: echo "No dependencies needed for pure SwiftUI project"
      - name: Build and archive iOS app
        script: |
          # Архівуємо додаток
          xcodebuild clean archive \
            -scheme LaserDetector \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/LaserDetector.xcarchive

          # Експортуємо .ipa
          xcodebuild -exportArchive \
            -archivePath $PWD/build/LaserDetector.xcarchive \
            -exportOptionsPlist $PWD/ExportOptions.plist \
            -exportPath $PWD/build/Release-iphoneos
    artifacts:
      - build/Release-iphoneos/LaserDetector.ipa
    publishing:
      email:
        recipients:
          - djdreamfix@gmail.com
