workflows:
  ios-laser-detector:
    name: LaserDetector iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release" # лишив для сумісності, можна видалити
    scripts:
      - name: Install dependencies
        script: echo "No dependencies needed for pure SwiftUI project"
      
      - name: Determine scheme and team ID
        script: |
          # Визначаємо схему
          scheme=$(xcodebuild -list -json | ruby -r json -e "puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo "Using scheme: $scheme"

          # Визначаємо Team ID із project.pbxproj
          project_file=$(ls *.xcodeproj | head -1)
          team_id=$(grep -m1 "DEVELOPMENT_TEAM" "$project_file/project.pbxproj" | awk -F' = ' '{print $2}' | tr -d '";')
          echo "Using Team ID: $team_id"

          echo $scheme > scheme.txt
          echo $team_id > team_id.txt

      - name: Clean & Archive iOS app
        script: |
          scheme=$(cat scheme.txt)
          team_id=$(cat team_id.txt)

          xcodebuild clean archive \
            -scheme "$scheme" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/LaserDetector.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$team_id"

      - name: Export .ipa
        script: |
          schem
