workflows:
  ios-laser-detector:
    name: LaserDetector iOS
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release" # залишено на випадок, якщо буде Flutter, інакше не впливає
    scripts:
      - name: Install dependencies
        script: echo "No dependencies needed for pure SwiftUI project"

      - name: Set variables
        script: |
          # Визначаємо файл для збірки
          if ls *.xcworkspace 1> /dev/null 2>&1; then
            filetype="workspace"
            file=$(ls *.xcworkspace | head -1)
          else
            filetype="project"
            file=$(ls *.xcodeproj | head -1)
          fi
          echo "Building file: $file ($filetype)"

          # Визначаємо схему
          scheme=$(xcodebuild -list -"$filetype" "$file" -json | ruby -r json -e "puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo "Using scheme: $scheme"

          # Визначаємо Team ID (для автоматичного підпису)
          team_id=$(grep -m1 "DEVELOPMENT_TEAM" "$file/project.pbxproj" | awk -F' = ' '{print $2}' | tr -d '";')
          echo "Using Team ID: $team_id"

          echo "FILE=$file" >> $CM_ENV_FILE
          echo "FILETYPE=$filetype" >> $CM_ENV_FILE
          echo "SCHEM
