workflows:
  ios-laser-detector:
    name: LaserDetector
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Install dependencies
        script: echo "No dependencies needed for pure SwiftUI project"
      - name: Build iOS app
        script: |
          xcodebuild clean archive \
            -scheme LaserDetector \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/LaserDetector.xcarchive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/LaserDetector.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/Release-iphoneos
    artifacts:
      - build/Release-iphoneos/LaserDetector.ipa
    publishing:
      email:
        recipients:
          - djdreamfix@gmail.com
