name: Xcode - Build and Analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v3
        with:
          xcode-version: '16.4' # або інша версія, яка підтримує macOS 11+

      - name: Build
        run: |
          # Задаємо схему, якщо у проекті тільки одна
          scheme=$(xcodebuild -list -json | jq -r '.project.schemes[0]')
          echo "Using scheme: $scheme"

          # Визначаємо workspace чи project
          if ls *.xcworkspace 1> /dev/null 2>&1; then
            filetype="workspace"
            file=$(ls *.xcworkspace)
          else
            filetype="project"
            file=$(ls *.xcodeproj)
          fi

          echo "Building $file ($filetype)..."

          # Збірка з аналізом для macOS 11+
          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -$filetype "$file" \
            -destination "platform=macOS,arch=arm64" \
            MACOSX_DEPLOYMENT_TARGET=11.0 | xcpretty
