name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        id: set_scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          default=$(echo "$scheme_list" | ruby -r json -e '
            data = JSON.parse(STDIN.read)
            if data["projects"]
              puts data["projects"].values.first["targets"].first
            elsif data["workspaces"]
              puts data["workspaces"].values.first["schemes"].first
            else
              abort("Cannot find project or workspace in JSON")
            end
          ')
          echo "Default scheme: $default"
          echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV

      - name: Build
        run: |
          scheme=$DEFAULT_SCHEME
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "Building scheme: $scheme in $file_to_build"
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
