name: SwiftUI iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      IOS_SDK: iphonesimulator18.5
      DEVICE: "iPhone 15"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Build for iOS Simulator
        run: |
          swift build --destination <(
            cat <<EOF
            {
              "sdk": "${IOS_SDK}",
              "arch": "arm64"
            }
            EOF
          )

      - name: Run Tests on iOS Simulator
        run: |
          SIMCTL=$(xcrun simctl list devices available | grep "${DEVICE}" | head -1 | awk -F '[()]' '{print $2}')
          xcodebuild test \
            -scheme LaserDetector \
            -destination "id=${SIMCTL}" \
            | xcpretty
