name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    # Кешування Swift пакетів та збірки
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: |
